[NextGIS]
Connect\cache\duration=30
Connect\cache\size=12288
Connect\editing\notifyWhenDeletingFeaturesWithAttachments=true
Connect\other\debugEnabled=false
Connect\other\debugNetworkEnabled=false
Connect\other\did_last_launch_fail=false
Connect\resources\addLayerAfterServiceCreation=true
Connect\resources\openWebMapAfterCreation=true
Connect\search\lastUsedType=by_display_name
Connect\search\metadataKeys=@Invalid()
Connect\uploading\addResourceCreationMetadata=true

[PythonPlugins]
Mergin=true
MetaSearch=false
QgisModelBaker=true
brdrq=false
grassprovider=false
linking_relation_editor=true
lizmap=true
nextgis_connect=true
oslandia=true
profile_manager=true
qfieldsync=true
qfit=true
db_manager=false

[QFieldSync]
cloudDirectory=/home/florent/QField/cloud
exportDirectory=/home/florent/QField/export
firstRun=false
importDirectory=/home/florent/QField/import
qfieldCloudRememberMe=false
qfieldCloudServerUrl=https://app.qfield.cloud/
qfieldCloudServerUrlsHistory=@Invalid()
showPackagingActions=true

[UI]
Customization\enabled=true
displayWaylandWarning=false
defaultNewLayer=2
defaultVertexTool=ActiveLayer
encoding=UTF-8

[app]
check-version=false

[connections]
ows\items\wms\connections\items\Swisstopo\authcfg=
ows\items\wms\connections\items\Swisstopo\dpi-mode=7
ows\items\wms\connections\items\Swisstopo\feature-count=10
ows\items\wms\connections\items\Swisstopo\http-header=@Variant(\0\0\0\b\0\0\0\0)
ows\items\wms\connections\items\Swisstopo\ignore-axis-orientation=false
ows\items\wms\connections\items\Swisstopo\ignore-get-feature-info-uri=false
ows\items\wms\connections\items\Swisstopo\ignore-get-map-uri=false
ows\items\wms\connections\items\Swisstopo\invert-axis-orientation=false
ows\items\wms\connections\items\Swisstopo\password=
ows\items\wms\connections\items\Swisstopo\reported-layer-extents=false
ows\items\wms\connections\items\Swisstopo\smooth-pixmap-transform=false
ows\items\wms\connections\items\Swisstopo\tile-pixel-ratio=0
ows\items\wms\connections\items\Swisstopo\url="https://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml?lang=en"
ows\items\wms\connections\items\Swisstopo\username=
ows\items\wms\connections\selected=Swisstopo
vector-tile\items\Swisstopo%20Basemap\authcfg=
vector-tile\items\Swisstopo%20Basemap\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
vector-tile\items\Swisstopo%20Basemap\password=
vector-tile\items\Swisstopo%20Basemap\styleUrl=https://vectortiles.geo.admin.ch/styles/ch.swisstopo.basemap.vt/style.json
vector-tile\items\Swisstopo%20Basemap\url=https://tiles.openfreemap.org/planet/20260913_164504_pt/{z}/{x}/{y}.pbf
vector-tile\items\Swisstopo%20Basemap\username=
vector-tile\items\Swisstopo%20Basemap\zmax=14
vector-tile\items\Swisstopo%20Basemap\zmin=0
vector-tile\items\Swisstopo%20Light%20Basemap\authcfg=
vector-tile\items\Swisstopo%20Light%20Basemap\http-header=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0r\0\x65\0\x66\0\x65\0r\0\x65\0r\0\0\0\n\0\0\0\0)
vector-tile\items\Swisstopo%20Light%20Basemap\password=
vector-tile\items\Swisstopo%20Light%20Basemap\styleUrl=https://vectortiles.geo.admin.ch/styles/ch.swisstopo.lightbasemap.vt/style.json
vector-tile\items\Swisstopo%20Light%20Basemap\url=https://tiles.openfreemap.org/planet/20260913_164504_pt/{z}/{x}/{y}.pbf
vector-tile\items\Swisstopo%20Light%20Basemap\username=
vector-tile\items\Swisstopo%20Light%20Basemap\zmax=14
vector-tile\items\Swisstopo%20Light%20Basemap\zmin=0
xyz\items\Mapzen%20Global%20Terrain\http-header=@Variant(\0\0\0\b\0\0\0\0)
xyz\items\OpenStreetMap\http-header=@Variant(\0\0\0\b\0\0\0\0)

[lizmap]
allow_parent_folder=false
beginner_mode=true
force_pg_user_password=true
lizmap_web_client_version=3.11
number_parent_folder=2
prevent_drive=true
prevent_ecw=true
prevent_pg_auth_db=true
prevent_pg_service=true

[plugin-manager]
allow-experimental=true
automatically-check-for-updates=true

[qfit]
ui\collapsed_groups=advancedOptionsGroup, layoutGroup, temporalGroup
ui\wizard_version=1

[qgis]
allowVersionCheck=false
checkVersion=false
warnOldProjectVersion=false
newProjectDefault=true
projOpenAtLaunch=3
projOpenAtLaunchPath=/home/florent/.local/share/QGIS/QGIS3/profiles/QGIS User Conference 2026/default_project/qgis-uc-2026.qgz
projectTemplateDir=/home/florent/.local/share/QGIS/QGIS3/profiles/QGIS User Conference 2026/project_templates

[qgsbrowserwidgetbase]
expandedPaths=favorites:, wms:, vectortile:

[svg]
searchPathsForSVG=/usr/share/qgis/svg/, /home/florent/.local/share/QGIS/QGIS3/profiles/QGIS User Conference 2026/svg/

[variables]
mergin_full_name=
mergin_url=
mergin_user_email=
mergin_username=
mm_full_name=
mm_url=
mm_user_email=
mm_username=

; For QGIS 4.2+
[project]
new-project-default=true
proj-open-at-launch=3
proj-open-at-launch-path=
ask-to-save-project-changes=true
warn-old-project-version=false